/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleAspects;

public class App {
    public static void main(String[] args) {
        Entity e = new Entity();
        System.out.println(e);
    }
}
